  
[[headers]]
for = "/*"

[headers.values]
Access-Control-Allow-Origin = "*"
            Referrer-Policy = "strict-origin-when-cross-origin"
  Strict-Transport-Security = "max-age=15768000"
     X-Content-Type-Options = "nosniff"
            X-Frame-Options = "DENY"
           X-XSS-Protection = "1; mode=block"
         Permissions-Policy = "autoplay=(), camera=(), geolocation=(), microphone=()"

[[headers]]
  for = "/img/*.png"
  
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Cache-Control = "public, max-age=604800"
    Content-Type = "image/png"

[[headers]]
  for = "/img/*.jpg"
  
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Cache-Control = "public, max-age=604800"
    Content-Type = "image/jpeg"

[[headers]]
  for = "/assets/*.ttf"
  
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Cache-Control = "public, max-age=604800"
    Content-Type = "application/font-ttf"

[[redirects]]
  from = "https://arieldiaz.netlify.com/*"
  to = "https://arieldiaz.codes/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://arieldiaz.netlify.app/*"
  to = "https://arieldiaz.codes/:splat"
  status = 301
  force = true

[[plugins]]
package = "netlify-plugin-csp-generator"

  [plugins.inputs]
  buildDir = "dist"

  [plugins.inputs.policies]
    defaultSrc = "'none'"
    scriptSrc = "'self' 'unsafe-inline' 'unsafe-eval' *.cloudfront.net cdn.jsdelivr.net unpkg.com *.netlifystatus.com"
    styleSrc = "'self' 'unsafe-inline' *.cloudfront.net *.gstatic.com *.googleapis.com cdn.jsdelivr.net unpkg.com *.netlifystatus.com"
    fontSrc = "'self' 'unsafe-inline' *.gstatic.com *.googleapis.com *.cloudfront.net"
    frameSrc = "'self' *.cloudfront.net"
    imgSrc = "'self' data: blob: *.cloudfront.net"
    manifestSrc = "'self' *.cloudfront.net *.netlifystatus.com"
    mediaSrc = "'self' *.cloudfront.net"
    objectSrc = "'self' *.cloudfront.net *.netlifystatus.com"
    prefetchSrc = "'self' *.gstatic.com *.googleapis.com *.cloudfront.net cdn.jsdelivr.net unpkg.com *.netlifystatus.com"
    scriptSrcElem = "'self' 'unsafe-inline' *.cloudfront.net unpkg.com *.netlifystatus.com"
    scriptSrcAttr = "'self' 'unsafe-inline' *.cloudfront.net cdn.jsdelivr.net unpkg.com *.netlifystatus.com"
    styleSrcElem = "'self' 'unsafe-inline' *.gstatic.com *.googleapis.com *.cloudfront.net"
    styleSrcAttr = "'self' 'unsafe-inline' *.gstatic.com *.googleapis.com *.cloudfront.net cdn.jsdelivr.net unpkg.com *.netlifystatus.com"
    workerSrc = "'self' *.cloudfront.net *.netlifystatus.com"
    baseUri = "'self' *.cloudfront.net"
    formAction = "'self' *.cloudfront.net *.netlifystatus.com"
    frameAncestors = "'self' *.cloudfront.net"
    connectSrc = "'self' 'unsafe-inline' blob: *.netlifystatus.com"

[[plugins]]
package = "@netlify/plugin-sitemap"

  [plugins.inputs]
  buildDir = "dist"
  exclude = [
    './dist/404', './dist/thanks', './dist/admin'
  ]