[[plugins]]
package = "netlify-plugin-csp-generator"

  [plugins.inputs]
  buildDir = "dist"

  [plugins.inputs.policies]
    defaultSrc = "'self' cloudfront.net *.cloudfront.net"
    scriptSrc = "'self' cloudfront.net *.cloudfront.net cdn.jsdelivr.net"
    styleSrc = "'self' 'unsafe-inline' cloudfront.net *.cloudfront.net *.gstatic.com *.googleapis.com cdn.jsdelivr.net"
    fontSrc = "'self' *.gstatic.com *.googleapis.com"
    imgSrc = "'self' data: blob:  *.shields.io"

[[headers]]
for = "/*"

  [headers.values]
    Access-Control-Allow-Origin = "*"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=31536000"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Permissions-Policy = "autoplay=(), camera=(), geolocation=(), microphone=()"

[[headers]]
  for = "/img/*.png"

  [headers.values]
    Cache-Control = "public, max-age=604800"
    Content-Type = "image/png"

[[headers]]
  for = "/img/*.jpg"

  [headers.values]
    Cache-Control = "public, max-age=604800"
    Content-Type = "image/jpeg"

[[headers]]
  for = "/assets/*.ttf"

  [headers.values]
    Cache-Control = "public, max-age=604800"
    Content-Type = "application/font-ttf"

[[headers]]
  for = "/favicon.ico"

  [headers.values]
    Cache-Control = "public, max-age=86400"
    Content-Type = "application/x-icon"

[[headers]]
for = "/sw.js"

  [headers.values]
    Cache-Control = "no-cache"

[[redirects]]
  from = "/tags"
  to = "/blog"
  status = 301
  force = true

[[redirects]]
  from = "/form.html"
  to = "/"
  status = 301
  force = true

[[redirects]]
  from = "https://arieldiaz.netlify.com/*"
  to = "https://arieldiaz.codes/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://arieldiaz.netlify.app/*"
  to = "https://arieldiaz.codes/:splat"
  status = 301
  force = true

[context.deploy-preview]
  ignore = "git log -1 --pretty=%B | grep dependabot"

[context.production]
    [[context.production.plugins]]
    package = "netlify-plugin-image-optim"
