[[plugins]]
package = "netlify-plugin-csp-generator"

  [plugins.inputs]
  buildDir = "dist"

  [plugins.inputs.policies]
    defaultSrc = "'none'"
    scriptSrc = "'self' 'unsafe-inline' 'unsafe-eval' *.cloudfront.net cdn.jsdelivr.net"
    styleSrc = "'self' 'unsafe-inline' *.cloudfront.net *.gstatic.com *.googleapis.com cdn.jsdelivr.net"
    fontSrc = "'self' 'unsafe-inline' *.gstatic.com *.googleapis.com *.cloudfront.net"
    frameSrc = "'self' *.cloudfront.net"
    imgSrc = "'self' data: blob: *.cloudfront.net *.shields.io"
    manifestSrc = "'self' *.cloudfront.net"
    mediaSrc = "'self' *.cloudfront.net"
    objectSrc = "'self' *.cloudfront.net"
    prefetchSrc = "'self' *.gstatic.com *.googleapis.com *.cloudfront.net cdn.jsdelivr.net"
    workerSrc = "'self' *.cloudfront.net"
    baseUri = "'self' *.cloudfront.net"
    formAction = "'self' *.cloudfront.net"
    frameAncestors = "'self' *.cloudfront.net"
    connectSrc = "'self'"

[[headers]]
for = "/*"

[headers.values]
Access-Control-Allow-Origin = "*"
            Referrer-Policy = "strict-origin-when-cross-origin"
  Strict-Transport-Security = "max-age=15768000"
     X-Content-Type-Options = "nosniff"
            X-Frame-Options = "DENY"
           X-XSS-Protection = "1; mode=block"
         Permissions-Policy = "autoplay=(), camera=(), geolocation=(), microphone=()"

[[headers]]
  for = "/img/*.png"

  [headers.values]
    Access-Control-Allow-Origin = "*"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Cache-Control = "public, max-age=604800"
    Content-Type = "image/png"

[[headers]]
  for = "/img/*.jpg"

  [headers.values]
    Access-Control-Allow-Origin = "*"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Cache-Control = "public, max-age=604800"
    Content-Type = "image/jpeg"

[[headers]]
  for = "/assets/*.ttf"

  [headers.values]
    Access-Control-Allow-Origin = "*"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Cache-Control = "public, max-age=604800"
    Content-Type = "application/font-ttf"

[[redirects]]
  from = "/tags"
  to = "/blog"
  status = 301
  force = true

[[redirects]]
  from = "/form.html"
  to = "/"
  status = 301
  force = true

[[redirects]]
  from = "https://arieldiaz.netlify.com/*"
  to = "https://arieldiaz.codes/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://arieldiaz.netlify.app/*"
  to = "https://arieldiaz.codes/:splat"
  status = 301
  force = true

[context.deploy-preview]
  ignore = "git log -1 --pretty=%B | grep dependabot"

[context.production]
    [[context.production.plugins]]
    package = "netlify-plugin-image-optim"
