backend:
  name: git-gateway
  branch: master
media_folder: 'static/img'
public_folder: '/img'
collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'content/posts'
    create: true
    slug: '{{slug}}'
    sort: 'date:desc'
    fields:
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - {
          label: Summary (50-200 characters max),
          name: summary,
          widget: text,
          required: true,
          pattern: ['.{50,220}', 'Must be within 50 and 200 characters'],
        }
      - { label: 'Publish Date', name: 'date', widget: 'date', required: true }
      - {
          label: 'Updated Date',
          name: 'update',
          widget: 'date',
          required: false,
        }
      - { label: 'Body', name: 'body', widget: 'markdown', required: true }
