name: Latest blog post
on:
  repository_dispatch:
    types: [blog.post]

jobs:
  update-readme-with-blog:
    name: Update GitHub profile README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull in blog posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: 'https://arieldiaz.codes/feed.xml'
